ALLOW_ORIGIN=
ALLOW_IP=
AUTHN_HEADER=X-Auth-Token
AUTHN_TOKEN=dev-local-token
CPU_EXTRA_TIME=1
CPU_TIME_LIMIT=2
ENABLE_COMMAND_LINE_ARGUMENTS=false
ENABLE_COMPILER_OPTIONS=false
ENABLE_NETWORK=false
ENABLE_WAIT_RESULT=true
MAX_CPU_EXTRA_TIME=2
MAX_CPU_TIME_LIMIT=5
MAX_FILE_SIZE=1024
MAX_MAX_FILE_SIZE=2048
MAX_MEMORY_LIMIT=256000
MAX_PROCESSES_AND_OR_THREADS=60
MAX_QUEUE_SIZE=100
MEMORY_LIMIT=128000
POSTGRES_DB=judge0
POSTGRES_HOST=judge0-db
POSTGRES_PASSWORD=judge0
POSTGRES_PORT=5432
POSTGRES_USER=judge0
REDIS_HOST=judge0-redis
REDIS_PASSWORD=judge0-redis-password
REDIS_PORT=6379
SECRET_KEY_BASE=dev-judge0-secret-key-base
USE_DOCS_AS_HOMEPAGE=true
WALL_TIME_LIMIT=5
